
<div>
<?php if ($block->checkPayApiConfiguration() && $block->getIsInstantBuyEnabled()) {?>
<script>
require(['jquery'],function($){

    var $btnClicked = $("#payapi-instantbutton");
    $btnClicked.click(function(evt){
        evt.preventDefault();
        var jsonData = {
            "referenceQuoteId": window.checkoutConfig.quoteItemData[0].quote_id,
            "ipaddress":"<?php echo $block->escapeHtml($block->getVisitorIp()); ?>"
        };
        $.ajax({
            showLoader: true,
            type: "POST",
            url: "/payapipages/index/secureformgenerator",
            data: jsonData,
            success: function(object){
              var form = document.createElement('form');
              form.style.display = 'none';
              form.setAttribute('method', 'POST');
              form.setAttribute('action', object.url);
              form.setAttribute('enctype', 'application/json');

              var input = document.createElement('input');
              input.name = 'data';
              input.type = 'text';
              input.setAttribute('value', object.data);

              form.appendChild(input);
              document.getElementsByTagName('body')[0].appendChild(form);
              form.submit();
            }
        });
    });
});
</script>
  <button id="payapi-instantbutton" class="action primary checkout" style="margin-right:10px">
    <span><?php echo $block->escapeHtml(__('Instant Buy')) ?></span>
</button>
<?php }?>
</div>
