<div class="test">

<?php if ($block->checkPayApiConfiguration()) {?>

<script>
if(typeof _payapi == "undefined"){
 var _payapi = {};
}

_payapi.addtocart = function _addtocart(url){
      var $addForm = $("#product_addtocart_form");
      if($addForm.length == 0){
       $addForm = $("a.fngrsharesdk-product[href='"+url+"']").parent().find("form[data-role='tocart-form'], button[data-role='tocart'], button.tocart");
       console.log($addForm);
      }
      if($addForm.length >= 1){
       if($addForm.first().is("form")){
        $addForm.first().submit();      
       }else{
        $addForm.first().click();
       }

      }else{
       alert("Product was not added to the cart");
      }
    };


var _fngrshareConfig = {
   isStaging: function _isStaging(){
     return <?php echo ($block->getIsStaging()); ?>;
   },
   enablePurchases: function _enablePurchases(){
    return <?php echo ($block->getIsInstantBuyEnabled()); ?>;
   },
   shortenerClientId: function _shortenerClientId(){
    return "<?php echo $block->escapeHtml($block->getPublicId()) ?>";
   }
  };
 require(['jquery'],function($){
  require(['fngrtouch','fngrui','fngrsdk'],function(){

   <?php if ($block->getIsStaging()) {?>
    payapiActions.isStaging = true;
   <?php } else {?>
    payapiActions.isStaging = false;
   <?php }?>

    $("a.product-item-photo").addClass("fngrsharesdk-product");

   <?php if ($block->getIsInstantBuyEnabled()) {?>

   var itemsIds = {
     "itemsIds": []
   };

   $(".price-box:not(.product-info-price .price-box)").after(function(){
     var id = $(this).attr('data-product-id');
     itemsIds["itemsIds"].push(id);
      return "<div class='actions'><button data-qty='1' data-mandatory='0' "
      + "id='payapi-button" + id +"' "
      + "class='action primary payapi-button' style='margin:10px;'>"
      + "<span><?php echo $block->escapeHtml(__('Instant Buy')) ?></span>"
      + "</button></div>";
   });

   if (itemsIds.itemsIds.length > 0)
   $.ajax({
    showLoader:false,
    type: "POST",
    url: "/payapipages/index/checkmandatoryfields",
    data: itemsIds,
    success: function(data){
      $.each(data, function(key, value) {
         if(value[1] == 0){
          var item = $("#payapi-button"+key).parent().find('.fngrsharesdk-product');
            if(item.length > 0){
             console.log("case 1");
             item.removeClass("fngrsharesdk-product");
            }else{
             console.log("case 2");
             item = $("#payapi-button"+key).closest(".product-item-info").find('.fngrsharesdk-product');
             console.log(JSON.stringify(item));
             item.removeClass("fngrsharesdk-product");
            }
            $("#payapi-button"+key).remove();
         }else{
          $("#payapi-button"+key).attr('data-mandatory',value[0]);
          $("#payapi-button"+key).attr('data-qty',value[1]);
         }

      });
      $(".fngrsharesdk-product").each(function(){
         var href = $(this).attr('href');
         if (href && href.indexOf("payapiwebshop") < 0 ){

          if (href.indexOf("?") >= 0 ){
           href = href + '&payapiwebshop='+((_fngrshareConfig.isStaging())?'1':'0')+'&ip=<?php echo $block->escapeHtml($block->getVisitorIp()); ?>';
          } else {
           href = href + '?payapiwebshop='+((_fngrshareConfig.isStaging())?'1':'0')+'&ip=<?php echo $block->escapeHtml($block->getVisitorIp()); ?>';
          }

          href = href + '&hasMandatory=' + $(this).parent().find('button.payapi-button').attr('data-mandatory');
          href = href + '&qty=' + $(this).parent().find('button.payapi-button').attr('data-qty');

          $(this).attr('href', href);
          $(this).closest("div.product-item-info").attr("fngrsharesdk-product-container",href);
         }
       });

      $(".product-item-link").each(function(){
        var href = $(this).closest(".product-item-info").find('.fngrsharesdk-product').attr('href');
        $(this).attr('href', href);
      });
    }
   });


   $(".payapi-button").click(function(evt){
            evt.preventDefault();
            var productUrl = $(this).parent().parent().find('.fngrsharesdk-product').attr('href');
            if(!productUrl){
              productUrl = $(this).closest(".product-item-info").find('.fngrsharesdk-product').attr('href');
            }
            if ($(this).attr('data-mandatory') !== "1"){
              var domain = (payapiActions.isStaging)? "staging-input.payapi.io" : "input.payapi.io";
              window.location = 'https://'+domain+'/v1/webshop/'+ encodeURIComponent(productUrl);
            } else {
              window.location = productUrl+"&fngr=1";
            }
          });

   window.setTimeout(function(){
          $("#top-cart-btn-checkout").after(
           "<button class='action primary checkout' style='margin:10px' id='payapi-mini-instantbuy'><span><?php
echo $block->escapeHtml(__('Instant Buy')) ?></span></button>");
          var $btnClicked = $("#payapi-mini-instantbuy");
    $btnClicked.click(function(evt){
           evt.preventDefault();
           var jsonData = {
               "ipaddress":"<?php echo $block->escapeHtml($block->getVisitorIp()); ?>"
           };
           $.ajax({
               showLoader: true,
               type: "POST",
               url: "/payapipages/index/secureformgenerator",
               data: jsonData,
               success: function(object){
                  var form = document.createElement('form');
                  form.style.display = 'none';
                  form.setAttribute('method', 'POST');
                  form.setAttribute('action', object.url);
                  form.setAttribute('enctype', 'application/json');

                  var input = document.createElement('input');
                  input.name = 'data';
                  input.type = 'text';
                  input.setAttribute('value', object.data);

                  form.appendChild(input);
                  document.getElementsByTagName('body')[0].appendChild(form);
                  form.submit();
               }
           });
       });

      },5000);

   <?php }?>

  });
   });


</script>
<?php }?>
</div>
