
<div>
<?php if ($block->checkPayApiConfiguration()) {
    if ($block->getInstantBuyBlock()->getIsInstantBuyEnabled()) {
        ?>

  <script>

    function getDynamicOptionsVals(){
      var $toCartForm = $("#product_addtocart_form");
      var configurableProdStock = <?php echo $block->getStockForConfigurableProduct() ?>;
        var stockVals = [0,0,0];
        if ("order" in configurableProdStock) {

          var attrsForm = $toCartForm.find(":input.super-attribute-select").serializeArray();
          var auxAttrs = [];
          attrsForm.forEach (function(item){
            auxAttrs[item.name] = item.value;
          });
          attrsForm = $toCartForm.find(":input.swatch-input").serializeArray();
          attrsForm.forEach (function(item){
            auxAttrs[item.name] = item.value;
          });
          attrsForm = auxAttrs;
          console.log(JSON.stringify(attrsForm));

          var strStockVals = "";

          configurableProdStock.order.forEach (function(optionId){
            strStockVals = strStockVals + optionId+":"+ attrsForm["super_attribute["+ optionId +"]"] + "&";
          });

          stockVals = configurableProdStock.attrs[strStockVals];
        }else{
          stockVals = "<?php echo $block->getStockItem()->getQty() . ","
        . $block->getStockItem()->getMinSaleQty() . ","
        . $block->getStockItem()->getMaxSaleQty() . ",0," . $block->getPriceInclTax(); ?>".split(",").map(Number);

      }
      return stockVals;
    }
  var _payapi = {
    checkMandatory: function _checkMandatory(url,silencePopup,msg, partial = false){
        var $toCartForm = $("#product_addtocart_form");
        var isValid = $toCartForm.validation('isValid');
        if (!isValid){
            if (!silencePopup){
              alert(msg);
            }
          return '';
        }

        //Add product options to the currUrl
        var opts = decodeURIComponent($toCartForm.find(":input:not(:hidden)").serialize());

        if(partial) {
          opts = opts + "&partialPayment=1";
        }

        var stockVals = getDynamicOptionsVals();
        console.log(stockVals);

          var curQty = $("#qty").attr("value");
          var $messages = $(".page-messages.messages");
          if (curQty > stockVals[0]) {
              $messages.empty();
              var msg = "<?php echo $block->escapeHtml($block->getStockMessage(0)); ?>";
              $messages.prepend("<div class='message-error error message'>"+msg+"</div>");
              alert($(".message-error").text());
              return '';
          }
          if (curQty < stockVals[1]) {
              $messages.empty();
              var msg = "<?php echo $block->escapeHtml($block->getStockMessage(1, false)); ?>";
              msg = msg.replace("%1", stockVals[1]);
              $messages.prepend("<div class='message-error error message'>"+msg+"</div>");
              alert($(".message-error").text());
              return '';
          } else if (curQty > stockVals[2]) {
              $messages.empty();
              var msg = "<?php echo $block->escapeHtml($block->getStockMessage(2, false)); ?>";
              msg = msg.replace("%1", stockVals[2]);
              $messages.prepend("<div class='message-error error message'>"+msg+"</div>");
              alert($(".message-error").text());
              return '';
          }
        var separator = "&";
        if(url.indexOf("?") < 0){
          separator = "?";
        }

        if (silencePopup){
          return url+separator+opts;
        }
        var productUrl = "<?php echo ($block->getInstantBuyBlock()->getIsStaging()) ? 'https://staging-input.payapi.io/v1/webshop/' : 'https://input.payapi.io/v1/webshop/'; ?>";
        productUrl = productUrl + encodeURIComponent(url+separator+opts);
        window.location = productUrl;
    }
  };
  </script>
<?php
if ($block->getSecureFormData() && count($block->getSecureFormData()->products) > 1) {
            $partialPay = $block->getInstantBuyBlock()->getPhpSdk()->partialPayment($block->getSecureFormData()->products[0]->priceInCentsIncVat * $block->getSecureFormData()->products[0]->quantity, $block->getSecureFormData()->order->currency);?>

<meta name="io.payapi.webshop" content="<?php
echo $block->escapeHtml($block->getInstantBuyBlock()->getPublicId()); ?>">
<meta name="order.currency" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->order->currency); ?>">
<meta name="order.shippingHandlingFeeInCentsExcVat" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[1]->priceInCentsExcVat); ?>">
<meta name="order.shippingHandlingFeeInCentsIncVat" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[1]->priceInCentsIncVat); ?>">
<meta name="order.tosUrl" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->order->tosUrl); ?>">
<?php if ($partialPay && $partialPay['code'] == 200 && $block->isPartialPaymentUrl()) { ?>
  <meta name="order.preselectedPartialPayment" content="<?php
echo $block->escapeUrl($partialPay['data']['paymentMethod']); ?>">
<?php }?>
<meta name="product.id" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->id); ?>">
<meta name="product.quantity" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->quantity); ?>">
<meta name="product.title" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->title); ?>">
<meta name="product.imageUrl" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->products[0]->imageUrl); ?>">
<meta name="product.priceInCentsIncVat" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->priceInCentsIncVat); ?>">
<meta name="product.priceInCentsExcVat" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->priceInCentsExcVat); ?>">
<meta name="product.vatInCents" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->vatInCents); ?>">
<meta name="product.vatPercentage" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->products[0]->vatPercentage); ?>">
<meta name="product.hasMandatoryFields" content="<?php
echo $block->escapeHtml($block->checkMandatoryFields()); ?>">
<meta name="consumer.email" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->consumer->email); ?>">
<meta name="consumer.locale" content="<?php
echo $block->escapeHtml($block->getSecureFormData()->consumer->locale); ?>">
<meta name="callbacks.processing" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->callbacks->processing); ?>">
<meta name="callbacks.success" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->callbacks->success); ?>">
<meta name="callbacks.failed" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->callbacks->failed); ?>">
<meta name="callbacks.chargeback" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->callbacks->chargeback); ?>">
<meta name="returnUrls.success" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->returnUrls->success); ?>">
<meta name="returnUrls.cancel" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->returnUrls->cancel); ?>">
<meta name="returnUrls.failed" content="<?php
echo $block->escapeUrl($block->getSecureFormData()->returnUrls->failed); ?>">
<?php } else {
            $partialPay = $block->getInstantBuyBlock()->getPhpSdk()->partialPayment($block->getPriceInclTax() * 100, $block->getCurrentCurrencyCode());
        }?>
<meta name="product.extraData" content="<?php
echo $block->escapeHtml($block->getExtraData()); ?>">
<button id="payapi-button" class="action primary" style="margin-top:10px; font-size: 16px;
    text-transform: uppercase;
    font-weight: 500;
    padding: 10px 20px;">
  <span><?php echo $block->escapeHtml(__('Instant Buy')) ?></span>
</button>
<?php }?>
<div id="partialpay-container">
<?php
if ($partialPay && $partialPay['code'] == 200) {
        ?>
  <button id="payapi-partpay-button" class="action primary" style="margin-top:10px; font-size: 16px;
    text-transform: uppercase;
    font-weight: 500;
    padding: 10px 20px;">
  <span><?php echo $block->escapeHtml(str_replace("##", ($partialPay['data']['pricePerMonthInCents'] / 100.0) . ' ' . $block->getCurrentCurrencyCode(), __('Starting from ##/month'))) ?></span>
</button>
<?php }?>
</div>
<script type="text/javascript">

     _payapi.partialPaymentEnabledForProduct = function _partialPayment(url){
      //Returns true if the product received as url has partial payment enabled
      return $("#payapi-partpay-button").length > 0;
    };
  require(['jquery','mage/translate'],function($){
        $(".fngrsharesdk-container").addClass("fngrsharesdk-productpage");
        var msg = $.mage.__("Please fill in all of the required fields");

        var $btnClicked = $("#payapi-button");
          $btnClicked.click(function(evt){
            evt.preventDefault();
            _payapi.checkMandatory(location.href,false,msg);
          });
          var $btnClickedPartial = $("#payapi-partpay-button");
          $btnClickedPartial.click(function(evt){
            evt.preventDefault();
            _payapi.checkMandatory(location.href,false,msg,true);
          });

          $("#product_addtocart_form").change(function(evt){
            var $toCartForm = $("#product_addtocart_form");
            var isValid = $toCartForm.validation('isValid');
            if(isValid){
              var optionData = getDynamicOptionsVals();
              console.log(optionData);
              if(optionData && optionData.length > 4) {
                var curQty = $("#qty").attr("value");
                console.log("Total: " + (optionData[4] * curQty));
          var jsonData = {
                   "total" : optionData[4]*100*curQty
                    };
          $.ajax({
                      showLoader: true,
                      type: "POST",
                      url: "/payapipages/index/checkpartialpayments",
                      data: jsonData,
                      success: function(object){
                        console.log(object);
                        if(object.code == 200){
                          if($("#payapi-partpay-button").length == 0){
                            $("#partialpay-container").append(
                              $(document.createElement('button'))
                          .addClass('action primary').attr('id','payapi-partpay-button')
                          .attr('style',"margin-top:10px; font-size: 16px; text-transform: uppercase; font-weight: 500;padding: 10px 20px;")
                          .click(function(evt) {
                            evt.preventDefault();
                            _payapi.checkMandatory(location.href,false,msg,true);
                          }).append($(document.createElement('span'))));

                          }
                          var strPartial = "<?php echo $block->escapeHtml(__('Starting from ##/month')); ?>";
                          strPartial = strPartial.replace("##",(object.data.pricePerMonthInCents/100.0)+' '+object.data.currency);
                          console.log(strPartial);
                          $("#payapi-partpay-button span:first-child").text(strPartial);
                        } else {
                          $("#payapi-partpay-button").remove();
                        }

                      }
                  });
                }
              }
                });


  });
</script>

<?php }?>

</div>
